// auto-generated by pytocpp convert.py
// output for 1st example by savir singh

#include <bits/stdc++.h>
using namespace std;

int main() {

int a = 5;
int b = 10;
int c =  a+b;
int d = 15;
string string1 =  "hello";


cout << c*d << endl;

cout << string1 << endl;





}
