// auto-generated by pytocpp convert.py
// output for 1st example by savir singh

#include <bits/stdc++.h>
using namespace std;

int main() {
int a ;
cin >> a ;int b ;
cin >> b ;
int c =  a*b;
for (int i=0; i<c; i++) {    cout << "Variable 'c' is equal to "  <<  c << endl;

}
}
